import {
  CamDoorbell,
  Cameras,
  CamFloodlight,
  CamFloodlightBlack,
  CamFloodlightWhite,
  CamPan,
  CamPanBlack,
  CamPanWhite,
  CamPro,
  CamProBlack,
  CamProWhite,
  CamV4,
  CamV4Black,
  CamV4Gray,
  CamV4White,
  ExtraProtection,
  Plan,
  Sensors,
} from "../../assets";
import type { BundleStep, SeededReviewItem } from "../types/types";

export const bundleSteps: BundleStep[] = [
  {
    id: "cameras",
    stepNumber: 1,
    title: "Choose your cameras",
    nextLabel: "Next: Choose your plan",
    category: "cameras",
    icon: Cameras,
    products: [
      {
        id: "wyze-cam-v4",
        stepId: "cameras",
        category: "cameras",
        title: "Wyze Cam v4",
        description: "The clearest Wyze Cam ever made.",
        image: CamV4,
        badge: "Save 22%",
        learnMore: "Learn More",
        compareAtPrice: 35.98,
        price: 27.98,
        variants: [
          {
            id: "white",
            name: "White",
            image: CamV4White,
          },
          {
            id: "gray",
            name: "Gray",
            image: CamV4Gray,
          },
          {
            id: "black",
            name: "Black",
            image: CamV4Black,
          },
        ],
      },
      {
        id: "wyze-cam-pan-v3",
        stepId: "cameras",
        category: "cameras",
        title: "Wyze Cam Pan v3",
        description: "360° pan and 180° tilt security camera.",
        image: CamPan,
        badge: "Save 30%",
        learnMore: "Learn More",
        compareAtPrice: 39.98,
        price: 34.98,
        variants: [
          {
            id: "white",
            name: "White",
            image: CamPanWhite,
          },
          {
            id: "black",
            name: "Black",
            image: CamPanBlack,
          },
        ],
      },
      {
        id: "wyze-video-floodlight-v2",
        stepId: "cameras",
        category: "cameras",
        title: "Wyze Cam Floodlight v2",
        description:
          "2K floodlight camera with a 160° wide-angle view for your garage.",
        image: CamFloodlight,
        learnMore: "Learn More",
        compareAtPrice: 89.98,
        price: 69.98,
        variants: [
          {
            id: "white",
            name: "White",
            image: CamFloodlightWhite,
          },
          {
            id: "black",
            name: "Black",
            image: CamFloodlightBlack,
          },
        ],
      },
      {
        id: "wyze-video-doorbell-v2",
        stepId: "cameras",
        category: "cameras",
        title: "Wyze Video Doorbell v2",
        description: "Answer your door from anywhere.",
        image: CamDoorbell,
        learnMore: "Learn More",
        compareAtPrice: 49.98,
        price: 39.98,
      },
      {
        id: "wyze-battery-cam-pro",
        stepId: "cameras",
        category: "cameras",
        title: "Wyze Battery Cam Pro",
        description:
          "Protect anywhere. See everything in 2.5K HDR. No power outlet or electrician needed. ",
        image: CamPro,
        learnMore: "Learn More",
        price: 89.98,
        variants: [
          {
            id: "white",
            name: "White",
            image: CamProWhite,
          },
          {
            id: "black",
            name: "Black",
            image: CamProBlack,
          },
        ],
      },
    ],
  },
  {
    id: "plan",
    stepNumber: 2,
    title: "Choose your plan",
    nextLabel: "Next: Choose your sensors",
    category: "plan",
    icon: Plan,
    products: [],
  },
  {
    id: "sensors",
    stepNumber: 3,
    title: "Choose your sensors",
    nextLabel: "Next: Add extra protection",
    category: "sensors",
    icon: Sensors,
    products: [],
  },
  {
    id: "protection",
    stepNumber: 4,
    title: "Add extra protection",
    nextLabel: "Review your system",
    category: "accessories",
    icon: ExtraProtection,
    products: [],
  },
];

export const seededReviewItems: SeededReviewItem[] = [];

// export const seededReviewItems: SeededReviewItem[] = [
//   {
//     productId: "home-monitoring-plan",
//     category: "plan",
//     title: "Home Monitoring Plan",
//     image: "/images/plan.png",
//     price: 9.99,
//     compareAtPrice: 14.99,
//     quantity: 1,
//   },
//   {
//     productId: "entry-sensor",
//     category: "sensors",
//     title: "Entry Sensor",
//     image: "/images/sensor.png",
//     price: 23.98,
//     compareAtPrice: 29.98,
//     quantity: 2,
//   },
//   {
//     productId: "keypad",
//     category: "accessories",
//     title: "Keypad",
//     image: "/images/keypad.png",
//     price: 19.98,
//     compareAtPrice: 24.98,
//     quantity: 1,
//   },
// ];
